### ISSUE TITLE
Applicable License?

### ISSUE THREAD

**Issue by jbaehr** [andersforsgren/DirectoryPackage#2]
Hi @andersforsgren,

Under which license your code may be used? So far I haven't found any information about this in your repo. I consider porting it to .NET Standard 2.0 (for usage in .NET Framework and .NET Core), provided there is a permissive license (preferably MIT, just like the .NET code from Microsoft).

**Comment by andersforsgren** [comment]
Hi, 

Yes MIT.

Added a License file now.

**Comment by andersforsgren** [comment]
Update to netstandard (and core/SDK project format) would be welcome if you want to make a PR.

**Comment by jbaehr** [comment]
Thanks. I'll have a look.

**Comment by jbaehr** [comment]
> Update to netstandard (and core/SDK project format) would be welcome if you want to make a PR.

Here you go: https://github.com/andersforsgren/DirectoryPackage/pull/3
