### ISSUE TITLE
Internal lock file not removed on closing

### ISSUE THREAD

**Issue by jbaehr** [andersforsgren/DirectoryPackage#6]
Right now the `DirectoryPackage` ctor creates a lock-file `_DirectoryPackage_lock` in the root directory of the extracted package. However, it is not removed when the directory package instance is closed/disposed [just closed](https://github.com/andersforsgren/DirectoryPackage/blob/b026e8c8d49d21689b57ebfb5eba2ecb4b9aa478/DirectoryPackage/DirectoryPackage.cs#L195).

This results in this lock file still laying around when re-zipping the directory. As a consequence, without counter measured in the calling code, an invalid OPC package is created: The lock file is treated by other readers as ordinary part (which is bad on its own) where there is no content type defined for.
The .NET API just ignores this "part". The [Go API](https://github.com/qmuntal/opc), however refuses to read such a package.

(as a side note: it would be better to use a name for the lock-file which is not a valid part name, to avoid conflicts. I suggest `[DirectoryPackage].lock`, following the naming rationale of the `[ContentTyps].xml` outlined in the OPC spec)

**Comment by andersforsgren** [comment]
Good find. Should delete it. I'm not sure the rename should be necessary as it really should never end up in the package. If it does end up in the package and is then extracted then the package won't be opened...

Perhaps the lockfile isn't necessary at all and the lib can just hold a file open exclusively for one of the core files of the package such as the content types file, to prevent others from opening the same package (the way the zip file usually works)

**Comment by andersforsgren** [comment]
I have a PR that gets rid of the lockfile. Try it out from the branch if you want. I'll merge it after the weekend.

**Comment by andersforsgren** [comment]
Done. I don't have an active use-case for this lib so I wouldn't find out if there are any issues with this solution. Open another issue if this doesn't work (E.g. if you want to manipulate the content-types file manually that would be more difficult with this solution). 
Thanks.

**Comment by jbaehr** [comment]
Thanks a lot!
The diff looks promising, but it may take a few days till I can give real-world feedback.
